version: '3'
services:
    mysqldb:
        image: mysql:${DB_VERSION}
        container_name: mysql-${APP_NAME}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - "${DATA_MYSQL}:/var/lib/mysql"
   