version: '2'

services:

    # nginx:
    #     image: nginx:latest
    #     ports:
    #         - 8000:80
    #     volumes:
    #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     # depends_on:
    #     volumes_from:
    #         - php

    # php:
    #     build: ./docker/php/
    #     volumes:
    #         - .:/var/www/html
    #         - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    #     links:
    #         - database
    #         - redis

    #     environment:
    #         - "DB_PORT=3306"
    #         - "DB_HOST=database"

     
    database:
        image: mysql:${DB_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - "${DATA_MYSQL}:/var/lib/mysql"

    redis:
        image: redis:4.0
        ports:
            - "6382:6379"

